version: "3"
services:
  api:
    depends_on:
      - db
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
        - .:/app # This is the line that mounts the local directory to the container
    command:
      - /bin/bash
      - -c
      - "./docker-entrypoint.sh"

  db:
    image: "postgres:16"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sre-bootcamp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:

