version: "3"
services:

  db:
    image: "postgres:16"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sre-bootcamp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api_1:
    depends_on:
      db:
        condition: service_healthy
    build: .
    env_file:
      - .env
    volumes:
        - .:/app # This is the line that mounts the local directory to the container
    command: bash ./docker-entrypoint.sh

  api_2:
    depends_on:
      - db
      - api_1
    build: .
    env_file:
      - .env
    volumes:
        - .:/app # This is the line that mounts the local directory to the container
    command: bash ./docker-entrypoint.sh

  nginx:
    image: nginx
    depends_on:
      - api_1
      - api_2
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:

