name: Build docker image and push to registry

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      AZURE_URL: ${{ secrets.AZURE_URL }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_URL}}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.AZURE_URL }}/sre-bootcamp:${{ github.sha }}
